---
sudo: false
cache: bundler
language: ruby

rvm:
  - 2.1.0

script:
  - bundle exec rake

notifications:
  email:
    recipients:
      - sky4winder+githubchangeloggenerator@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
